services:
  # Sets up how to make the source data available
  demo: {}
  tms: {}
  wmts: {}
  wms:
    # SRS sets the coordinate reference systems to make data available
    srs: ['EPSG:4326', 'EPSG:3857']
    image_formats: ['image/jpeg', 'image/png']

layers:
  # Sets up which layers you want to make available using the services above
  - name: world_phys_clipped_trans
    title: world_phys_clipped_trans Layer
    sources: [world_phys_clipped_trans_cache]


caches:
  # Sets up how to cache the source data

  world_phys_clipped_trans_cache:
    grids: [world_phys_clipped_trans_grid]
    sources: [world_phys_clipped_trans_source]
    format: image/png


sources:
  world_phys_clipped_trans_source:
    type: tile
    url: https://map.casariolab.art/geoserver/gwc/service/tms/1.0.0/workspace1:world_phys_clipped_trans@EPSG:900913@png/%(z)s/%(x)s/%(y)s.png
    grid: world_phys_clipped_trans_grid_reverse

grids:
  world_phys_clipped_trans_grid:
    base: GLOBAL_MERCATOR
    srs: 'EPSG:3857'
    origin: nw

  world_phys_clipped_trans_grid_reverse:
    base: GLOBAL_MERCATOR
    srs: 'EPSG:3857'
    origin: sw

globals:

  cache:
    # Where to store the cached images
    base_dir: './cache_data'
    # Where to store lockfiles
    lock_dir: './cache_data/locks'

  image:
    # Image/transformation options
    resampling_method: bilinear
    jpeg_quality: 90

